[package]
name = "in-memory-cache"
version = "0.1.0"
edition = "2018"
authors = ["Đorđe Zeljić <zeljic@gmail.com>"]

[dependencies.anyhow]
version = "1"

[dependencies.bytes]
version = "1.1"

[profile.release]
lto = true